site_name: Quiz Game Library
site_url: https://jsq081.github.io/my-project/

nav:
    - Home: index.md
    - API: api.md
    - Getting Started: getStarted.md
    - Demo Example :  https://quiz-game-jsqqq.herokuapp.com/

theme: readthedocs
